### ISSUE TITLE
Default class initializers

### ISSUE THREAD

**Issue by inumanag** [seq-lang/seq#100]
This segfaults:
```
class X:
   y: dict[int, int]
   def __init__(self: X):
       pass
X.y[1]
```

Maybe `__init__` should call default constructor on all members? We don't want segfaults or uninitialized values in Seq.

**Comment by arshajii** [comment]
I think the broader issue is what to do about `None`s (right now `None` will segfault in general). I'd propose that in debug mode we always add a check whenever we dereference a class variable (this is easy to do in the backend) and raise an exception if it's `None`.

**Comment by arshajii** [comment]
Added with https://github.com/seq-lang/seq/commit/ac3a73e6091f144b8cd71c77a75f79e0586847d6.
