### ISSUE TITLE
FASTA/Q names

### ISSUE THREAD

**Issue by inumanag** [seq-lang/seq#101]
For FASTQ file
```
@SRR2040271.1 SN603_WBP007_8_1101_63.30_99.90 length=100
NTCATTCCATGACATTGTCTGTTGGTTGCTTTTTGAGTATATTTTCTCATGGCTTCATCTATCTTGCTCATAAGACTAAATGGGGAGACAGACTTCCTGG
+SRR2040271.1 SN603_WBP007_8_1101_63.30_99.90 length=100
!1=DDFFFGHHHHIJJJJJIIJJJGGHJGJIJJGBGGHEGHJIIIIEHIJEH>@G;FHCG<<BCG:CG@F4@D@=@DG>EE>EED(,,(;((,;;@A>CC
@SRR2040271.1 SN603_WBP007_8_1101_63.30_99.90 length=100
AGACTTCAGACTACCACAGAGCCCACACAGCCAGGAAGTCTGTCTCCCCATTTAGTCTTATGAGCAAGATAGATGAAGCCATGAGAAAATATACTCAAAA
+SRR2040271.1 SN603_WBP007_8_1101_63.30_99.90 length=100
CCCFFFFFHHHGHJIIJIIIJJJIIJJJIJIJGIIJJJHIIJHIJIJJJJIJJJIHGIJJJJIIIGIIJHGHHHHFEEEECEEECEDDCCCDEEEDDDCD
@SRR2040271.2 SN603_WBP007_8_1101_79.90_99.30 length=100
NTAAAGACCCTTCAACTCAGGGCTTCTGAACCCTGGCTACCCATTAGAATCACTTAGGGAGCTTTGAAAAATATCAACACCCCAGCCCTAACCCAGCCCA
```

`record.name` is `SRR2040271.1 SN603_WBP007_8_1101_63.30_99.90 length=100` while it should be `SRR2040271.1` (everything after the space is a comment). Maybe introduce `comment` property?

**Comment by arshajii** [comment]
Good point; I think we can rename current `name` to `header` for full header line, then introduce `@property`s `name` and `comment` that split on the space and return the correct string. That way there's not extra storage and you only split the string on demand.

**Comment by arshajii** [comment]
Added with https://github.com/seq-lang/seq/commit/02d468111ebd469f58800fe90330110f1249f9b1.
