### ISSUE TITLE
Segfault with chained generators

### ISSUE THREAD

**Issue by arshajii** [seq-lang/seq#102]
Reproduce with:

```python
n = 1

def foo(x: generator[int]) -> int:
    for a in x:
        yield 0

def bar(n: int) -> int:
    i = 0
    while i < n:
        yield 0
        i += 1

def baz() -> int:
    for a in foo(bar(n)):  # <-- using 1 here inline avoids segfault
        yield a

for a in baz():
    print a
```

**Comment by inumanag** [comment]
This is similar to the problem I had with HTx!

**Comment by arshajii** [comment]
After some testing, it seems LLVM 7 works (our Tapir-LLVM is based on LLVM 6 due to [a regression](https://bugs.llvm.org/show_bug.cgi?id=40656) in 7+). After looking at the changes to LLVM coroutines, I believe this was fixed with [this](https://github.com/llvm-mirror/llvm/commit/dcb2807d870458afa2a505b290ebb6f459c32c26#diff-466cda1fa7219a86168156d5ebfca802) commit. We could easily port this to our LLVM fork, but we'll need to make sure it isn't the cause of said regression itself!

**Comment by inumanag** [comment]
Anecdotally, this has been resolved on our Tapir branch (https://github.com/seq-lang/Tapir-LLVM) as I experienced no issues since the latest fix.
