### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/xz/lib/liblzma.5.dylib

### ISSUE THREAD

**Issue by fuzzthink** [seq-lang/seq#103]
Installed seq a week ago on osx catalina 10.15, all is good.

Try to install on osx 10.13.6 today, via:
```
wget -O - https://raw.githubusercontent.com/seq-lang/seq/master/install.sh | bash
# updated & sourced .bash_profile as instructed.
brew install libomp
```

`seqc test.seq` # just print 's'

got
```
dyld: Library not loaded: /usr/local/opt/xz/lib/liblzma.5.dylib
  Referenced from: /Users/johnleung/.seq/seqc
  Reason: Incompatible library version: seqc requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0
Abort trap: 6
```

`/usr/local/opt/` does not contain `xz/`

**Comment by inumanag** [comment]
`brew install xz`?
Probably Travis  uses the latest version of `liblzma` that is used for building `htslib`.

**Comment by fuzzthink** [comment]
`brew install xz` installed `liblzma.5.dylib  liblzma.a        liblzma.dylib` into `/usr/local/opt/xz/lib/liblzma`, but still seeing:

```
dyld: Library not loaded: /usr/local/opt/xz/lib/liblzma.5.dylib
  Referenced from: /Users/johnleung/.seq/seqc
  Reason: Incompatible library version: seqc requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0
Abort trap: 6`
```

Seems like the latest liblzma.5 (6.0) is many years ago. Why seqc wants 8.0? How can 8.0 be installed?

**Comment by inumanag** [comment]
Fixed! Thanks for the report!
