### ISSUE TITLE
Bug? s'A'[:] errors

### ISSUE THREAD

**Issue by fuzzthink** [seq-lang/seq#109]
```
print s'A'[1:]  # ok
print s'A'[:]   # errors
```

test.seq:2:9: error: cannot find method '__getitem__' for type 'seq' with specified argument types (eslice)

**Comment by arshajii** [comment]
This is something we could add to the `seq` type (note that it should work for `str`); it would just be a no-op.

**Comment by arshajii** [comment]
Added with https://github.com/seq-lang/seq/commit/f6ca8b6b3bf88364fc5fadf7c883a8489b73f15a.

**Comment by fuzzthink** [comment]
Thanks! @arshajii
