### ISSUE TITLE
Bug? Extended slice syntax errors on string

### ISSUE THREAD

**Issue by fuzzthink** [seq-lang/seq#113]
```python
print([3, 2, 1][::-1])  # ok, prints [3, 2, 1]

s = 'abc'
print(s[::-1])  # prints 'cba' in python but errors in seq
```

error: cannot find method '__getitem__' for type 'str' with specified argument types (esslice)

**Comment by arshajii** [comment]
Added with https://github.com/seq-lang/seq/commit/ae1384cdab890f888fe751d515bc50fd385726a8!
