### ISSUE TITLE
Seg Fault Issue

### ISSUE THREAD

**Issue by fuzzthink** [seq-lang/seq#114]
Create repo for a seq fault issue: https://github.com/fuzzthink/seqIssues

Error message:
`zsh: segmentation fault  ~/.seq/seqc segfault.seq 3`

Version: Seq 0.9.5

Main call is:
```python
if run(1):
   print cyclopeptidesSequencing(ints1)
if run(2):
   print cyclopeptidesSequencing(ints2)
if run(3):
   print cyclopeptidesSequencing(ints1)
   print cyclopeptidesSequencing(ints2)
```

`seqc segfault.seq 3` will run 2 functions, which seg faults.
But running 1 and 2 by itself will not.

**Comment by markhend** [comment]
`PeptideChars = MassLU.keys()` seems to be the issue.
`PeptideChars = list(MassLU.keys())` works

**Comment by fuzzthink** [comment]
@markhend Thank you!!
