### ISSUE TITLE
`in` optimization needed

### ISSUE THREAD

**Issue by inumanag** [seq-lang/seq#123]
`if len(name) > 2 and (name[-2] == '#' or name[-2] == '/')` is much faster than  `if len(name) > 2 and name[-2] in '#/'` (15 seconds difference on a small BAM). We might consider optimizing this case.

**Comment by arshajii** [comment]
I think this is probably just an `str.__contains__` issue. We can probably add special-cases when the pattern is single-character etc. Right it uses KMP search everywhere, which entails allocating the LP array etc. I think if the length of the query string is, say, <= 5 we can just do a brute force search.

**Comment by arshajii** [comment]
https://github.com/seq-lang/seq/commit/faa7b949efc82f98e3589b267f9b8e18c1b22cd9 adds this, and should be a lot faster for these kinds of single-character patterns.
