### ISSUE TITLE
`finally` does not work with `sys.exit`

### ISSUE THREAD

**Issue by inumanag** [seq-lang/seq#124]
In Python, this prints `hi`:

```
try:
  sys.exit(0)
finally:
  print('hi')
```

In Seq, it just terminates without going through `finally`. 

Should we handle exit signals gracefully?

**Comment by arshajii** [comment]
This is quite tricky. Even if we "catch" the exit, it's not easy to jump through all the pending `finally`s. Need to think more about how to solve this one...

`finally` in general makes things 10x more complicated, especially when you have abnormal control flow out of the corresponding `try` block (e.g. `break`, `continue`, `return` -- which are all handled correctly -- and now `exit`). https://seq-lang.org/internals.html#try-except-finally discusses how it works.

**Comment by arshajii** [comment]
After looking into how Python does this: in Python `sys.exit()` actually raises `SystemExit`, which allows `finally`s to be executed (https://docs.python.org/3/library/exceptions.html#SystemExit). I think we can do the same in Seq (and similarly for `assert`s).

**Comment by arshajii** [comment]
This is resolved with https://github.com/seq-lang/seq/commit/f25ac1cd929aa3badb5b1efa4c6ada91e390631a. Now both `sys.exit()` and `assert`s will call `finally` blocks.
