### ISSUE TITLE
Generator issues

### ISSUE THREAD

**Issue by inumanag** [seq-lang/seq#128]
- [x] Can we have `generator.__str__` like in Python?
- [x] `print range(10)[2:-2]` does not work...

**Comment by arshajii** [comment]
- https://github.com/seq-lang/seq/commit/5a4a79c31b5cff09045e3100a62d837490076447 adds `__str__` to generator and function types (gives something like `<function at 0x101b0da50>` or `<generator at 0x107970ec0>`).
- https://github.com/seq-lang/seq/commit/efca4fdefadc2702820028fad19ef6484cf53085 adds slice support for ranges (as well as a few other methods/features).
