### ISSUE TITLE
Compilation not working

### ISSUE THREAD

**Issue by c5sire** [seq-lang/seq#142]
Hello,

I am trying to produce an executable file as per the instructions on the intro page.
The first two steps 
  seqc -o myprogram.bc myprogram.seq
  llc myprogram.bc -filetype=obj -o myprogram.o
are working. However, the third step
   gcc -L/path/to/libseqrt/ -lseqrt -lomp -o myprogram myprogram.o
gives an error:

/usr/bin/ld: cannot find -lomp
collect2: error: ld returned 1 exit status

I installed 
 sudo apt-get install libomp-dev

but still the same.

Any thoughts?

Thank you

**Comment by jelber2** [comment]
I had to do the following instead of what was in the instructions:

     gcc -L/path/to/libseqrt/ -o myprogram myprogram.o -lseqrt -lomp

**Comment by c5sire** [comment]
Thank you, but still get the same error.

**Comment by jelber2** [comment]
Okay, sorry. Another thing I had to do on my system, Ubuntu 20.04, was make sure the symlink in directory /path/to/libseqrt/
was

    libomp.so -> /usr/lib/llvm-10/lib/libomp.so.5

and not

    libomp.so.5 -> /usr/lib/llvm-10/lib/libomp.so.5

**Comment by c5sire** [comment]
Hi,

that apparently solved one issue. But now it shows:
/usr/bin/ld: myprogram.o: relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIE
collect2: error: ld returned 1 exit status

**Comment by c5sire** [comment]
Thanks

**Comment by jelber2** [comment]
Try

    gcc -L/path/to/libseqrt/ -o myprogram myprogram.o -no-pie -lseqrt -lomp


Note, you might need to add `-lz` after `-lomp` if you are using libraries requiring `libz` (i.e., `zlib`)
You would need to have a symlink in /path/to/libseqrt/ such as

    libz.so.1 -> /lib/x86_64-linux-gnu/libz.so.1

**Comment by c5sire** [comment]
That worked!

Thanks for the notes and help.

Best

**Comment by jelber2** [comment]
Oh great! Have fun with `Seq`. I am not a `Seq` developer but went through the same issues as you presumably. It looks like a very promising programming language.

**Comment by inumanag** [comment]
Hi @c5sire,

Right now you will need to install Intel or LLVM OMP and link it via `-lomp` or `-lomp5` or `-liomp` (depending on your system). Make sure not to use GNU OMP (`-lgomp`) as it won't work.

We're currently working on making Seq binaries easier to generate and more portable. The next release will probably tackle this issue.

**Comment by c5sire** [comment]
Hi @inumanag,

thanks for the notes. Looking forward to the next release.
