### ISSUE TITLE
Seq and htslib 1.10.2

### ISSUE THREAD

**Issue by jelber2** [seq-lang/seq#143]
Hi,

I was wondering if it is possible to compile `Seq` with htslib 1.10.2 instead of htslib 1.9? Just curious.

**Comment by arshajii** [comment]
Seq re-implements a few of the structures from HTSlib, so as long as the layout of those structs (and the API of course) hasn't changed it should work -- I'll have to check if they actually changed anything though!

**Comment by jelber2** [comment]
Ok thank you very much!

**Comment by inumanag** [comment]
Actually, the latest version (at least on `develop`) **requires** 1.10+, and it loads it via `dylob` mechanism (so you ensure that correct htslib is in `LD_LIBRARY_PATH` or seq `SEQ_HTSLIB` to the library location). Not sure if this is true in the last `master` release though?
