### ISSUE TITLE
How to view which attributes are contained in a Seq object?

### ISSUE THREAD

**Issue by newcounts** [seq-lang/seq#146]
Hello, I now use seq-lang to process bam, but I can't find more seq-lang documentation. Because seq-lang is a subset of python, I have used the dir() and vars() functions in python to view those attributes, but it doesn’t seem to work. I want to know how to view the attributes of an object in  seq-lang.

Thank you

**Comment by arshajii** [comment]
Hi @newcounts, 
We're in the process now of creating documentation for the standard library, which should clearly list attributes and methods along with descriptions etc. This should be included with the next major release, which we're hoping to have done by the end of the month.

Adding `dir()` and `vars()` functions though is actually doable and probably a good idea; in our case these would be known statically at compile-time.

**Comment by arshajii** [comment]
Happy to inform you we've just released the first version of standard library documentation at https://docs.seq-lang.org/stdlib.

All (public) functions, classes, types and methods should be listed there. Most should have documentation / descriptions, although we're still in the process of adding more of that!

The `seq` type in particular is documented here: https://docs.seq-lang.org/stdlib/bio/seq.html
