### ISSUE TITLE
documentation?

### ISSUE THREAD

**Issue by parlar** [seq-lang/seq#150]
Just discovered seq-lang, good stuff!! 

I did not find any info on what libraries are actually available, what functions, classes. Some examples of working with vcf/bcf files would be very helpful.  Since it is a new tool/language it is understandable that documentation is lagging behind.

As I understand, only parsing of vcf/bcf files is implemented yet? (not writing)

**Comment by arshajii** [comment]
Hi there,
Yes this is definitely one of our top priorities right now. We're planning to make the next major release in the coming weeks, which will include auto-generated docs for the standard library (we'll add them to seq-lang.org). In the meantime though we can definitely add some VCF examples to the cookbook/tutorial -- it's a newer feature so we haven't gotten to documenting it fully yet. Right now, we mainly support just parsing of all the common formats (including VCF/BCF), but are hoping to implement some writing functionality down the line too.

**Comment by parlar** [comment]
Thanks, looking forward to the next release!

**Comment by arshajii** [comment]
Happy to inform you we've just released the first version of standard library documentation at https://docs.seq-lang.org/stdlib.

All (public) functions, classes, types and methods should be listed there. Most should have documentation / descriptions, although we're still in the process of adding more of that!
