### ISSUE TITLE
the links in readme are wrong

### ISSUE THREAD

**Issue by kkasra12** [seq-lang/seq#151]
the links in readme are pointing to seq-lang.org which are not correct they must point to docs.seq-lang.org

**Comment by arshajii** [comment]
We just put up our new website at https://seq-lang.org and moved the old site to https://docs.seq-lang.org. Both are working now on my side -- is it still not working for you?

**Comment by kkasra12** [comment]
yes both of them are working but check [this file](https://github.com/seq-lang/seq/blob/develop/README.md) where you have written `Learn more by following the tutorial or from the cookbook` those two links will raise 404 error.

**Comment by arshajii** [comment]
Ah, good point -- I just updated it. Thanks for pointing that out!

**Comment by kkasra12** [comment]
thanks
