### ISSUE TITLE
Expose setting gzip compression level support

### ISSUE THREAD

**Issue by ghuls** [seq-lang/seq#159]
Exposing setting gzip copression level support in a user friendly way. in `core/file.seq`:

zlib supports setting/changing the compression level with `gzFile` and `gzsetparams`

> ZEXTERN gzFile ZEXPORT gzopen OF((const char *path, const char *mode));
> 
> Opens a gzip (.gz) file for reading or writing. The mode parameter is as in fopen ("rb" or "wb") but can also include a compression level ("wb9") or a strategy: 'f' for filtered data as in "wb6f", 'h' for Huffman-only compression as in "wb1h", 'R' for run-length encoding as in "wb1R", or 'F' for fixed code compression as in "wb9F". (See the description of deflateInit2 for more information about the strategy parameter.) 'T' will request transparent writing or appending with no compression and not using the gzip format.
> 
> 'a' can be used instead of 'w' to request that the gzip stream that will be written be appended to the file. '+' will result in an error, since reading and writing to the same gzip file is not supported. The addition of 'x' when writing will create the file exclusively, which fails if the file already exists. On systems that support it, the addition of 'e' when reading or writing will set the flag to close the file on an execve() call.
> 
> These functions, as well as gzip, will read and decode a sequence of gzip streams in a file. The append function of gzopen() can be used to create such a file. (Also see gzflush() for another way to do this.) When appending, gzopen does not test whether the file begins with a gzip stream, nor does it look for the end of the gzip streams to begin appending. gzopen will simply append a gzip stream to the existing file.
> 
> gzopen can be used to read a file which is not in gzip format; in this case gzread will directly read from the file without decompression. When reading, this will be detected automatically by looking for the magic two-byte gzip header.
> 
> gzopen returns NULL if the file could not be opened, if there was insufficient memory to allocate the gzFile state, or if an invalid mode was specified (an 'r', 'w', or 'a' was not provided, or '+' was provided). errno can be checked to determine if the reason gzopen failed was that the file could not be opened.

> 
> ZEXTERN int ZEXPORT gzsetparams OF((gzFile file, int level, int strategy));
> 
> Dynamically update the compression level or strategy. See the description of deflateInit2 for the meaning of these parameters. Previously provided data is flushed before the parameter change.
> 
> gzsetparams returns Z_OK if success, Z_STREAM_ERROR if the file was not opened for writing, Z_ERRNO if there is an error writing the flushed data, or Z_MEM_ERROR if there is a memory allocation error. 

http://www.zlib.net/manual.html

**Comment by inumanag** [comment]
Hi @ghuls :

Yeah, this is something we should add— thanks for suggesting it! Just curious: does `gzopen('foo', 'wb9')` work or not?

**Comment by ghuls** [comment]
Yes it works. I tried it yesterday with gzip compression 4 and 5 and the output files were of different size.

```
with gzip.open(fastq_corrected_bc_filename, 'wb5') as fh_corrected_bc_fastq:
   ...
```

**Comment by ghuls** [comment]
It would also be nice if htslib bgzip compression could be exposed and used easily as it supports compressing blocks in parallel (at least bgzip supports it).

**Comment by ghuls** [comment]
zlib-ng has a major new release:
https://github.com/zlib-ng/zlib-ng/discussions/871

In my tests minigzip of zlib-ng is twice faster for decompressing a FASTQ that gzip and 4 times faster when compressing a FASTQ file.

**Comment by inumanag** [comment]
zlib-ng has been added to #132.
