### ISSUE TITLE
[Feature request] support more than 2 elements in core.builtin.zip()

### ISSUE THREAD

**Issue by dawe** [seq-lang/seq#165]
Hi all, I have a set of fastq split over 3 reads (R1, R2, R3) and I want to process them as in the [cookbook](https://docs.seq-lang.org/cookbook.html#reading-paired-end-fastq). I had an error as zip does not support more than two elements. For the time being I can process my data twice (R1  + R2 and R2 + R3), but I wonder if it would be possible to support more than two elements.

**Comment by inumanag** [comment]
Resolved in #132 . Thanks for proposing this!
