### ISSUE TITLE
Fail to run examples from the tutorial

### ISSUE THREAD

**Issue by xiangmy** [seq-lang/seq#218]
Hi,

Thanks for the great work! The example from the [pipeline section](https://docs.seq-lang.org/tutorial/tutorial.html#pipelines) in the tutorial fails to compile and run. The example code is like following:
```
dna = s'ACGTACGTACGT'  # sequence literal

# (a) split into subsequences of length 3
#     with a stride of 2
dna |> split(..., 3, 2) |> echo

# (b) split into 5-mers with stride 1
def f(kmer):
    print kmer
    print ~kmer

dna |> kmers[Kmer[5]](1) |> f
```
And the error was like:
```
$ seqc run test.seq 
test.seq:5:8: error: identifier 'split' not found
```

I suppose this is because the `split()` is only the built-in method for `str` but not a built-in function. Do you have any advice on how to make this example works?

Thanks,
Mingyuan

**Comment by markhend** [comment]
Hi Mingyuan! Glad you are trying it out. I have been working through some of the examples as well. Try adding `from bio import *` at the top. split() is in bio.builtin. This will help with some of the other examples too.

**Comment by xiangmy** [comment]
Hi @markhend ,

Thanks for the help! I'm closing the issue.

Thanks,
Mingyuan

**Comment by chklopp** [comment]
I have the same issue and the correction generates another error :

<pre>dna = s'ACGTACGTACGT'  # sequence literal

# (a) split into subsequences of length 3
#     with a stride of 2
dna |> split(..., 3, 2) |> echo

# (b) split into 5-mers with stride 1
def f(kmer):
    print kmer
    print ~kmer

dna |> kmers[Kmer[5]](1) |> f
</pre>
produces : <pre>kmer2.py:5:8: error: identifier 'split' not found</pre>

If i add 
<pre>from bio import *</pre>
at the top, I get : <pre>kmer2.py:13:8: error: cannot find '__getitem__' in std.bio.builtin.kmers[seq,int,k]</pre>
