### ISSUE TITLE
Parallel benchmark programs

### ISSUE THREAD

**Issue by xiangmy** [seq-lang/seq#219]
Hi,

I'm playing with the parallel feature with the seq library. However, I don't know where I can find the benchmark programs for the parallel feature. I tried to "grep" `||>`, and I only found an app named "cora" in `test/apps` as well as a test program for the parallel feature. So, I'm wondering whether there is any change I can obtain the benchmark programs mentioned in the paper, specifically, programs listed in the following table which I borrow from the seq paper.
![image](https://user-images.githubusercontent.com/48262740/120763289-a7986900-c549-11eb-93c8-7c11a02c7e58.png).

Thanks,
Mingyuan

**Comment by markhend** [comment]
Hi Mingyuan,
There is an older benchmarks [repo](https://github.com/seq-lang/benchmarks) which includes the programs mentioned in that paper. Please note, since Seq is young and evolving, those programs would likely require updating in order to run on the latest release, v0.10.1.

You might be interested in the [Workshop](https://docs.seq-lang.org/tutorial/workshop.html) which has a nice walk-through that includes demonstrating the benefits of `||>`.

**Comment by xiangmy** [comment]
Hi @markhend,

Thanks for the pointer! It saves my day.

Thanks,
Mingyuan

**Comment by xiangmy** [comment]
Hi,

Thanks for the pointer of seq benchmark repo as I'm studying the optimization techniques for seq. One weird thing happened when I was comparing the older version of seq from the VM provided in [Zenodo](https://zenodo.org/record/3374036) with the latest version (`v0.10.1`). The performance of the latest version is **35x slower** than the older one. I test the performance with `16mer/16mer.seq`, the 'Pythonic Seq' so called in the paper. Therefore, I guess there won't be many new features introduced to influence the performance. However, the performance results are quite surprising. I test the performance with `perf stat -d`, so that I can observe some of the cache performance.
With the `v0.10.1` seq (the built-from-source version), I compiled the code with `seqc build -exe 16mer.seq` and ran with a toy benchmark copied from the VM. I got:
```
xiangmy#build > perf stat -d ./16mer ../../benchmark_data/HG00123_small.txt
1023410176 63963136 263790

 Performance counter stats for './16mer ../../benchmark_data/HG00123_small.txt':

     107904.107863      task-clock (msec)         #    1.384 CPUs utilized
         1,259,962      context-switches          #    0.012 M/sec
           273,869      cpu-migrations            #    0.003 M/sec
             6,193      page-faults               #    0.057 K/sec
   145,143,191,008      cycles                    #    1.345 GHz
   <not supported>      stalled-cycles-frontend
   <not supported>      stalled-cycles-backend
   214,371,646,057      instructions              #    1.48  insns per cycle
    44,086,968,430      branches                  #  408.575 M/sec
       384,470,153      branch-misses             #    0.87% of all branches
    68,462,312,542      L1-dcache-loads           #  634.474 M/sec
     1,220,100,565      L1-dcache-load-misses     #    1.78% of all L1-dcache hits
       511,156,578      LLC-loads                 #    4.737 M/sec
        14,502,624      LLC-load-misses           #    2.84% of all LL-cache hits

      77.940216257 seconds time elapsed
```
Similar results can be produced with pre-built version.

With the VM version (running on my host machine), I copied the 16mer.seq binary, shared libraries, and `stdlib` to my host machine. I also needed to set some environment variables. Then, I ran with the same toy benchmark, and I got.:
```
1023410176 63963136 263790

 Performance counter stats for './16mer.seq benchmark_data/HG00123_small.txt':

       2097.830930      task-clock (msec)         #    1.078 CPUs utilized
             7,110      context-switches          #    0.003 M/sec
                50      cpu-migrations            #    0.024 K/sec
               457      page-faults               #    0.218 K/sec
     5,571,864,148      cycles                    #    2.656 GHz
   <not supported>      stalled-cycles-frontend
   <not supported>      stalled-cycles-backend
     8,788,177,358      instructions              #    1.58  insns per cycle
     1,651,014,917      branches                  #  787.010 M/sec
        86,394,412      branch-misses             #    5.23% of all branches
     1,599,957,781      L1-dcache-loads           #  762.672 M/sec
         9,317,779      L1-dcache-load-misses     #    0.58% of all L1-dcache hits
         3,791,234      LLC-loads                 #    1.807 M/sec
           734,467      LLC-load-misses           #   19.37% of all LL-cache hits

       1.945452142 seconds time elapsed
```
If I test the code on the VM, they are slightly slower than the above result, but it's reasonable

The results they produced are the same (`1023410176 63963136 263790`), so I suppose the programs are running 'correctly'. However, I don't know why there is a huge performance gap between the previous version and new one. One thing I found quite strange is the low cache hit rate with the latest version though I don't know why.

Do you have any insights behind the performance results?

Thanks,
Mingyuan

**Comment by arshajii** [comment]
Hi @xiangmy — new versions of Seq compile in debug mode by default, so you need the `-release` flag to enable optimizations. Are you using this flag on the newer version? The old VM version compiled in release mode by default.

**Comment by xiangmy** [comment]
Hi @arshajii ,

Thanks for the reply! I'm following [instructions from the github page](https://github.com/seq-lang/seq/blob/develop/docs/sphinx/build.rst#building-from-source), so I believe it's in the release mode. BTW, I attached the 'grep' results from the build directory.
```
xiangmy#build > grep -R Release | grep -v google
Binary file lib/libgtest.a matches
Binary file seqtest matches
CMakeCache.txt://Choose the type of build, options are: None Debug Release RelWithDebInfo
CMakeCache.txt:CMAKE_BUILD_TYPE:STRING=Release
cmake_install.cmake:    set(CMAKE_INSTALL_CONFIG_NAME "Release")
Binary file libseq.so matches
```

Thanks,
Mingyuan

**Comment by arshajii** [comment]
Oh sorry, I meant you should use `-release` when actually invoking `seqc`, as in `seqc build -release ...`.

**Comment by xiangmy** [comment]
Hi @arshajii ,

Thanks for the help. The latest version still runs **2x slower** than the old version. (I ran both versions again to make sure they were running under the same condition. And the old version produced similar results, so I won't paste them.)
```
1023410176 63963136 263790

 Performance counter stats for './16mer ../seq_benchmarks/benchmark_data/HG00123_small.txt':

       9181.267917      task-clock (msec)         #    1.935 CPUs utilized
            51,128      context-switches          #    0.006 M/sec
             2,197      cpu-migrations            #    0.239 K/sec
             2,442      page-faults               #    0.266 K/sec
    17,849,570,358      cycles                    #    1.944 GHz
   <not supported>      stalled-cycles-frontend
   <not supported>      stalled-cycles-backend
    22,146,914,654      instructions              #    1.24  insns per cycle
     5,840,000,673      branches                  #  636.078 M/sec
        82,457,959      branch-misses             #    1.41% of all branches
     5,188,294,230      L1-dcache-loads           #  565.096 M/sec
        12,241,147      L1-dcache-load-misses     #    0.24% of all L1-dcache hits
         4,927,264      LLC-loads                 #    0.537 M/sec
         1,049,546      LLC-load-misses           #   21.30% of all LL-cache hits

       4.744903560 seconds time elapsed
```
The LLC miss rate is slightly higher than the old one's. Does this relate to the prefetch stride tuning?

**Comment by arshajii** [comment]
In that case, this is quite surprising. This is the code you're running, right?

```python
import sys

def revcomp(c):
   return ('A' if c == 'T' else \
          ('C' if c == 'G' else \
          ('G' if c == 'C' else \
          ('T' if c == 'A' else c))))

def process(k):
   return len(k)

def ksplit(s, k, step):
   i = 0
   while i + k <= len(s):
      yield s[i:i + k]
      i += step

def sym(s, k):
   return 1 if all(s[i] == revcomp(s[-i-1]) for i in range(k//2)) else 0

f = open(sys.argv[1], 'r')
total, t2, t3 = 0, 0, 0
k = 16
for l in f:
   for s in ksplit(l.strip(), k, 1):
      total += process(s)
      t2 += 1
      t3 += sym(s, k)
print total, t2, t3
```

**Comment by xiangmy** [comment]
Hi @arshajii ,

I use the same program from the [VM](https://zenodo.org/record/3374036). The for loop at the bottom is different (`for s in ksplit(l, k, 1):`). The complete code is like following:
```
# 786
# benchmarks:
# - reverse complementing 10g FASTA
# - printing all 16-mers from 10g FASTA
# - count number of CpG islands (e.g. all CG-only subseqs)

import sys

def revcomp(c):
   return ('A' if c == 'T' else \
          ('C' if c == 'G' else \
          ('G' if c == 'C' else \
          ('T' if c == 'A' else c))))

def process(k):
   return len(k)

def ksplit(s, k, step):
   i = 0
   while i + k <= len(s):
      yield s[i:i + k]
      i += step

def sym(s, k):
   return 1 if all(s[i] == revcomp(s[-i-1]) for i in range(k//2)) else 0

f = open(sys.argv[1], 'r')
total, t2, t3 = 0, 0, 0
k = 16
for l in f:
   for s in ksplit(l, k, 1):
      total += process(s)
      t2 += 1
      t3 += sym(s, k)
print total, t2, t3
```

**Comment by arshajii** [comment]
Would it be possible to time a simplified version that doesn't include reverse complementation? This might let us identify the issue. e.g.

```python
import sys
total = 0
f = open(sys.argv[1], 'r')
for l in f:
   total += len(l)
print total
```

There shouldn't be any prefetching in this benchmark actually, and the memory usage should be low and constant (I wonder if this is the same between versions?).

**Comment by arshajii** [comment]
Actually I think I know what the difference is. The old version would not copy the internal buffer of `File` when returning the line -- this works fine most of the time, but is invalid if the line is stored somewhere and used later. We should actually have an IR pass to detect cases like this and avoid wasteful copying; this is a recurrent theme when reading sequences from disk as well.

If this theory is true, the code above should still be 2x slower in the new version.

**Comment by xiangmy** [comment]
Hi @arshajii ,

I think you are correct. The toy benchmark (HG00123_small.txt) is so small that it doesn't make any difference in both versions. However, I do observe a 5x slower in the new version if I run with HG00123_5mil.fq (786MB). Moreover, if I add `f.close()` at the end of the code, with the simplified version you mentioned above, the old version ran for 3.7s and the latest one ran for 4.3s. I'm not sure whether the 10% difference matters though it seems good to me.

**Comment by arshajii** [comment]
I see; the 5x could be from the GC, since the old version would never even have to invoke the GC whereas the new version does an allocation for each line of the input file. Usually this overhead is comparatively very small in real-world applications, where reading/copying lines would be a very small fraction of the runtime. Some of these early benchmarks are so simple though that things like this appear to have a huge effect.

Either way I think we can address some of these by doing analyses to figure out when to avoid copying, e.g. via some capture analysis.

**Comment by xiangmy** [comment]
Thanks for the clarification. I'm closing the issue.

**Comment by markhend** [comment]
Thanks for the detailed information Mingyuan.

**Comment by ghuls** [comment]
@arshajii does this copying of lines also happen when reading records of a FASTQ file with `FASTQ()`? I have some code that does some record oriented processing of FASTQ files, so if copying of lines can be avoided, it would be great.
