### ISSUE TITLE
Executing Seq fail after install

### ISSUE THREAD

**Issue by lhui2010** [seq-lang/seq#225]
Hello, 

I installed seq with recommended command `/bin/bash -c "$(curl -fsSL https://seq-lang.org/install.sh)"`. The install exited with no problem, and PATH were also added. But when executing, it reported errors with `symbol binding failed`.  Is there something wrong with library linking or just not compatible with my OS?

Thanks
Hui

--

OS: OS X 10.11.6.

```
bash-3.2$ seqc -help
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: ~/.seq/bin/seqc
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: ~/.seq/bin/seqc
  Expected in: /usr/lib/libSystem.B.dylib
```

**Comment by arshajii** [comment]
Hi @lhui2010 -- we compile the pre-built binaries on GitHub actions using their [virtual environments](https://github.com/actions/virtual-environments). Their macOS environment uses macOS 10.15 / Catalina, so it's possible the older 10.11 you're using will not work.

It may be possible to support these older versions on our end in future releases -- need to look into that.

In the meantime you could either upgrade to a newer macOS or build Seq from source (instructions [here](https://docs.seq-lang.org/build.html)).

**Comment by lhui2010** [comment]
Thanks!Hui-------- 原始邮件 --------发件人： "A. R. Shajii" ***@***.***>日期： 2021年7月24日周六 晚上10:53收件人： seq-lang/seq ***@***.***>抄送： Hui ***@***.***>, Mention ***@***.***>主    题： Re: [seq-lang/seq] Executing Seq fail after install (#225)
Hi @lhui2010 -- we compile the pre-built binaries on GitHub actions using their virtual environments. Their macOS environment uses macOS 10.15 / Catalina, so it's possible the older 10.11 you're using will not work.
It may be possible to support these older versions on our end in future releases -- need to look into that.
In the meantime you could either upgrade to a newer macOS or build Seq from source (instructions here).
