### ISSUE TITLE
https://seq-lang.org/demo docker instance failed

### ISSUE THREAD

**Issue by jpmam1** [seq-lang/seq#226]
Demo docker instance at https://seq-lang.org/demo is throwing an error.

```
docker: Error response from daemon: mkdir /var/lib/docker/overlay2/b7972a55959b3919d34843c2f5ad9541b0c75164bb5b24aeb3f5ad79e98fa829-init: no space left on device.
See 'docker run --help'.

```

**Comment by arshajii** [comment]
Thanks for the report, @jpmam1. Somehow the JSON log file had grown to nearly 15GB. I disabled logging and re-started the server; should work now!
