### ISSUE TITLE
Support for vcf file

### ISSUE THREAD

**Issue by MuhammedHasan** [seq-lang/seq#227]
Dear Seq Team,

This is awesome project. Thanks for your effort.

Can you provide support reading and processing vcf files  (something similar to https://github.com/brentp/cyvcf2)?

**Comment by arshajii** [comment]
Hi @MuhammedHasan, thanks for the kind words. We actually already support VCF, e.g.

```python
from bio import *
for record in VCF('test/data/toy.vcf'):
    print(record.chrom, record.qual, record.ref, list(record.alts))
```

More info about the VCF records here: https://docs.seq-lang.org/stdlib/bio/vcf.html#bio.vcf.VCFRecord. Let me know if this is what you were looking for!
