### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by saulobritto** [seq-lang/seq#229]
Hi,

I'm trying to install and use seq and I'm facing a problem that I could not solve.
I'm trying to install with the default command:
/bin/bash -c "$(curl -fsSL https://seq-lang.org/install.sh)"

stderr:
  _% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   147  100   147    0     0    308      0 --:--:-- --:--:-- --:--:--   307
100   631  100   631    0     0    896      0 --:--:-- --:--:-- --:--:--   896
seq-deploy/lib/
seq-deploy/lib/seq/
seq-deploy/lib/seq/libseq.so
 20 14.5M   20 2999k    0     0  2194k      0  0:00:06  0:00:01  0:00:05 2194kseq-deploy/lib/seq/libomp.so
seq-deploy/lib/seq/libseqrt.so
seq-deploy/lib/seq/stdlib/
seq-deploy/lib/seq/stdlib/sortedlist.seq
seq-deploy/lib/seq/stdlib/operator.seq
seq-deploy/lib/seq/stdlib/statistics.seq
seq-deploy/lib/seq/stdlib/threading.seq
seq-deploy/lib/seq/stdlib/sys.seq
seq-deploy/lib/seq/stdlib/time.seq
seq-deploy/lib/seq/stdlib/internal/
seq-deploy/lib/seq/stdlib/internal/sort.seq
seq-deploy/lib/seq/stdlib/internal/c_stubs.seq
seq-deploy/lib/seq/stdlib/internal/dlopen.seq
seq-deploy/lib/seq/stdlib/internal/file.seq
seq-deploy/lib/seq/stdlib/internal/attributes.seq
seq-deploy/lib/seq/stdlib/internal/__init_test__.seq
seq-deploy/lib/seq/stdlib/internal/builtin.seq
seq-deploy/lib/seq/stdlib/internal/khash.seq
seq-deploy/lib/seq/stdlib/internal/str.seq
seq-deploy/lib/seq/stdlib/internal/box.seq
seq-deploy/lib/seq/stdlib/internal/types/
seq-deploy/lib/seq/stdlib/internal/types/slice.seq
seq-deploy/lib/seq/stdlib/internal/types/int.seq
seq-deploy/lib/seq/stdlib/internal/types/array.seq
seq-deploy/lib/seq/stdlib/internal/types/byte.seq
seq-deploy/lib/seq/stdlib/internal/types/bool.seq
seq-deploy/lib/seq/stdlib/internal/types/error.seq
seq-deploy/lib/seq/stdlib/internal/types/str.seq
seq-deploy/lib/seq/stdlib/internal/types/float.seq
seq-deploy/lib/seq/stdlib/internal/types/ptr.seq
seq-deploy/lib/seq/stdlib/internal/types/optional.seq
seq-deploy/lib/seq/stdlib/internal/types/generator.seq
seq-deploy/lib/seq/stdlib/internal/types/range.seq
seq-deploy/lib/seq/stdlib/internal/types/collections/
seq-deploy/lib/seq/stdlib/internal/types/collections/dict.seq
seq-deploy/lib/seq/stdlib/internal/types/collections/list.seq
seq-deploy/lib/seq/stdlib/internal/types/collections/set.seq
seq-deploy/lib/seq/stdlib/internal/types/intn.seq
seq-deploy/lib/seq/stdlib/internal/python.seq
seq-deploy/lib/seq/stdlib/internal/internal.seq
seq-deploy/lib/seq/stdlib/internal/__init__.seq
seq-deploy/lib/seq/stdlib/internal/gc.seq
seq-deploy/lib/seq/stdlib/collections.seq
seq-deploy/lib/seq/stdlib/pickle.seq
seq-deploy/lib/seq/stdlib/string.seq
seq-deploy/lib/seq/stdlib/gzip.seq
seq-deploy/lib/seq/stdlib/itertools.seq
seq-deploy/lib/seq/stdlib/bisect.seq
seq-deploy/lib/seq/stdlib/getopt.seq
seq-deploy/lib/seq/stdlib/bio/
seq-deploy/lib/seq/stdlib/bio/kmer.seq
seq-deploy/lib/seq/stdlib/bio/bwa.seq
seq-deploy/lib/seq/stdlib/bio/prefetch.seq
seq-deploy/lib/seq/stdlib/bio/bed.seq
seq-deploy/lib/seq/stdlib/bio/fasta.seq
seq-deploy/lib/seq/stdlib/bio/bwt.seq
seq-deploy/lib/seq/stdlib/bio/types.seq
seq-deploy/lib/seq/stdlib/bio/intervals.seq
seq-deploy/lib/seq/stdlib/bio/locus.seq
seq-deploy/lib/seq/stdlib/bio/iter.seq
seq-deploy/lib/seq/stdlib/bio/builtin.seq
seq-deploy/lib/seq/stdlib/bio/c_htslib.seq
seq-deploy/lib/seq/stdlib/bio/align.seq
seq-deploy/lib/seq/stdlib/bio/pseq.seq
seq-deploy/lib/seq/stdlib/bio/fmindex.seq
seq-deploy/lib/seq/stdlib/bio/vcf.seq
seq-deploy/lib/seq/stdlib/bio/fai.seq
seq-deploy/lib/seq/stdlib/bio/fastq.seq
seq-deploy/lib/seq/stdlib/bio/block.seq
seq-deploy/lib/seq/stdlib/bio/seq.seq
seq-deploy/lib/seq/stdlib/bio/__init__.seq
seq-deploy/lib/seq/stdlib/bio/bam.seq
seq-deploy/lib/seq/stdlib/random.seq
seq-deploy/lib/seq/stdlib/functools.seq
seq-deploy/lib/seq/stdlib/python.seq
seq-deploy/lib/seq/stdlib/algorithms/
seq-deploy/lib/seq/stdlib/algorithms/qsort.seq
seq-deploy/lib/seq/stdlib/algorithms/heapsort.seq
seq-deploy/lib/seq/stdlib/algorithms/strings.seq
seq-deploy/lib/seq/stdlib/algorithms/pdqsort.seq
seq-deploy/lib/seq/stdlib/algorithms/timsort.seq
seq-deploy/lib/seq/stdlib/algorithms/insertionsort.seq
seq-deploy/lib/seq/stdlib/math.seq
seq-deploy/lib/seq/stdlib/heapq.seq
seq-deploy/lib/seq/stdlib/os/
seq-deploy/lib/seq/stdlib/os/path.seq
seq-deploy/lib/seq/stdlib/os/__init__.seq
seq-deploy/bin/
seq-deploy/bin/seqc
100 14.5M  100 14.5M    0     0  6189k      0  0:00:02  0:00:02 --:--:-- 11.2M
PATH export command:
  export PATH=/home/saulo/.seq/bin:$PATH
Could not find bash configuration file to update PATH
Seq successfully installed at: /home/saulo/.seq
Open a new terminal session or update your PATH to use seqc_

I did updated bash and exported the path to use it.
Then, always that I try to run a script ".seq" from docs tutorial, an error appear:
_Illegal instruction (core dumped)_

Thank you in advance for your help guys. I'm anxious to apply this language.

**Comment by saulobritto** [comment]
Additional info:

OS: Ubuntu 20.04.2 LTS
OS Type: 64-bit

**Comment by arshajii** [comment]
Hey @saulobritto -- does `seqc --help` work without error? The pre-built binary _should_ work on your system...

**Comment by saulobritto** [comment]
Same error. I tried it and --version too.
![image](https://user-images.githubusercontent.com/50638088/127909990-c92df505-375d-47f2-b603-3f1b7781c4d3.png)

**Comment by markhend** [comment]
What does `seqc --version` show?

**Comment by saulobritto** [comment]
![image](https://user-images.githubusercontent.com/50638088/127910797-641cfed4-0bfa-45fe-99f8-68fddbcce3be.png)

Same error.
I'm afraid it's something stupid of me, something basic I haven't done, despite following the default install instruction.

**Comment by inumanag** [comment]
Hi @saulobritto,

Can you please share the output of `cat /proc/cpuinfo`? This might be related to out build system (your CPU might not support some SSE intrinsics).

**Comment by saulobritto** [comment]
Sure. I even thought about this possibility at the beginning, but I ended up forgetting and I didn't put the information.
My CPU is really not new, let's say. Haha

_processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 23
model name	: Intel(R) Core(TM)2 Quad CPU    Q8300  @ 2.50GHz
stepping	: 10
microcode	: 0xa0b
cpu MHz		: 2003.000
cache size	: 2048 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 xsave lahf_lm pti tpr_shadow vnmi flexpriority vpid dtherm
vmx flags	: vnmi flexpriority tsc_offset vtpr vapic
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 5008.66
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 23
model name	: Intel(R) Core(TM)2 Quad CPU    Q8300  @ 2.50GHz
stepping	: 10
microcode	: 0xa0b
cpu MHz		: 2427.184
cache size	: 2048 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 4
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 xsave lahf_lm pti tpr_shadow vnmi flexpriority vpid dtherm
vmx flags	: vnmi flexpriority tsc_offset vtpr vapic
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 5008.66
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 23
model name	: Intel(R) Core(TM)2 Quad CPU    Q8300  @ 2.50GHz
stepping	: 10
microcode	: 0xa0b
cpu MHz		: 2003.000
cache size	: 2048 KB
physical id	: 0
siblings	: 4
core id		: 2
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 xsave lahf_lm pti tpr_shadow vnmi flexpriority vpid dtherm
vmx flags	: vnmi flexpriority tsc_offset vtpr vapic
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 5008.66
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 23
model name	: Intel(R) Core(TM)2 Quad CPU    Q8300  @ 2.50GHz
stepping	: 10
microcode	: 0xa0b
cpu MHz		: 2003.000
cache size	: 2048 KB
physical id	: 0
siblings	: 4
core id		: 3
cpu cores	: 4
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 xsave lahf_lm pti tpr_shadow vnmi flexpriority vpid dtherm
vmx flags	: vnmi flexpriority tsc_offset vtpr vapic
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 5008.66
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

_

**Comment by inumanag** [comment]
No SSE 4.2--- that's probably the reason.

For now, I'd recommend either building from source (currently PITA; will be massively simplified by the end of the month) or waiting for a new release (again, the end of the month) where we'll try to turn SSE4 off.

**Comment by saulobritto** [comment]
Ok, fine. Thanks for your support and attention!

**Comment by arshajii** [comment]
Hi @saulobritto this should be fixed in 0.10.3 (released yesterday). Feel free to reopen if the issue persists.
