### ISSUE TITLE
Example not working 

### ISSUE THREAD

**Issue by chklopp** [seq-lang/seq#244]
I have the same issue as [#218](https://github.com/seq-lang/seq/issues/218) and the correction generates another error :

<pre>dna = s'ACGTACGTACGT'  # sequence literal

# (a) split into subsequences of length 3
#     with a stride of 2
dna |> split(..., 3, 2) |> echo

# (b) split into 5-mers with stride 1
def f(kmer):
    print kmer
    print ~kmer

dna |> kmers[Kmer[5]](1) |> f
</pre>
produces : <pre>kmer2.py:5:8: error: identifier 'split' not found</pre>

If i add 
<pre>from bio import *</pre>
at the top, I get : <pre>kmer2.py:13:8: error: cannot find '__getitem__' in std.bio.builtin.kmers[seq,int,k]</pre>

**Comment by markhend** [comment]
Hi @chklopp - Thanks for reaching out. With version v0.11.0 we updated the syntax for calling some built-in functions, including kmers, to be more pythonic. You can check your version with `seqc --version`. The last line would now be:
`dna |> kmers(k=5, step=1) |> f`

We've updated the docs as well: https://docs.seq-lang.org/tutorial/tutorial.html#pipelines

**Comment by chklopp** [comment]
Works! Thank you.
