### ISSUE TITLE
index file from class FMIndex

### ISSUE THREAD

**Issue by xinrcornelia** [seq-lang/seq#251]
**Running Environment: seq is installed in another user's directory. And that user can successfully generate the .fai file.**

Hello, I used section2.seq to test building .fai file and output IOError:
'''
$ IOError: file ./xxx.fa.fai could not be opened
Raised from: std.internal.file.gzFile.__init__.3
.../local/lib/seq/stdlib/internal/file.seq:117:13
'''

Then i created .fai first and output IndexError:
'''
$ IndexError: list index out of range
Raised from: std.internal.types.ptr.List._idx_check
.../local/lib/seq/stdlib/internal/types/collections/list.seq:335:13
'''

**Comment by markhend** [comment]
Hi. What version of Seq are you using? (I'm using Seq version 0.11.0.)

How did you create the .fai file? As a troubleshooting step, you could download the files used in the [Workshop](https://docs.seq-lang.org/tutorial/workshop.html). There is an .fai file included. I just tried again with the curl command shown:
`curl -L https://www.dropbox.com/s/8lsngqvn0tzjn1o/data.tar.gz | tar zxf - -C .`

When I run `section2.seq` with `seqc run section2.seq data/chr22.fa` it outputs the index file `chr22.fa.index`.

**Comment by markhend** [comment]
You could also possibly try to build the index without using the .fai file. e.g.
`for record in FASTA(argv[1], fai=False):`

**Comment by xinrcornelia** [comment]
Hi Mark, thank you for your reply!  

I'm using version 0.11.0.  Fasta file could be parsing without .fai.

There is another question, does the magic method ___pickle__()_ in class _FMIndex_ will create a file for FM-Index? How can I use this method and find the result file?

**Comment by markhend** [comment]
This [example ](https://github.com/seq-lang/seq/blob/37b58696a411ac5867320dd3647fe50b958d2605/test/apps/bwa/fastmap.seq#L100)in test/apps/bwa/fastmap.seq might help.
