### ISSUE TITLE
Is seq-lang still being updated and maintained

### ISSUE THREAD

**Issue by dawnmy** [seq-lang/seq#259]
Thank you for design such an useful programming language for the biology world. It looks amazing. The repo seems to have no new commits for more than half a year. Was wondering if it is still being updated and maintained?

**Comment by ghuls** [comment]
Seq-lang itself is quite unlikely to be updated. The technology behind Seq-lang though lives on as Codon: https://exaloop.io/

**Comment by inumanag** [comment]
Hi @dawnmy 

It is alive. We are currently working on the next major version. Once that is done, we will update the repository.

**Comment by ghuls** [comment]
@inumanag Any rough timeframe (in a few weeks/months/half a year) for the next release?

The codon versions listed at: https://docs.exaloop.io/codon/general/releases seem private.

**Comment by arshajii** [comment]
Hey @ghuls and everyone -- we're just putting the finishing touches on everything now. Should be 1-2 more weeks roughly; sorry it was so drawn out, we just had a long list of things we wanted to do before releasing :) (I'll give an update here once we release as well.)

**Comment by arshajii** [comment]
Hi all, happy to announce that we just opened the Codon repo: https://github.com/exaloop/codon

All of Seq's bio features/libraries/optimizations are available as a Codon plugin here: https://github.com/exaloop/seq

I'll be archiving this repo but feel free to try out Codon and give feedback on the new GitHub link. Thanks!
